import { readFileSync } from "node:fs";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { pathToFileURL } from "node:url";

import type { GenerateClientWithAliasesOptions } from "./codegen.ts";
import {
  collectSchemaDefinitions,
  lowerFirst,
  paramsCanBeOmitted,
  pascal,
  receiverStickyParamFields,
  requiredSet,
  safeTypeName,
  sanitizeCommandRegistry,
  sanitizeRegistry,
  schemaPropertiesObject,
  sdkPath,
  sortedEntries,
  statelessAliasObjects,
  unionSchemas,
} from "./codegen_shared.ts";

export { generateClientWithAliasesForGo };

function generateClientWithAliasesForGo(options: GenerateClientWithAliasesOptions, objects, commands) {
  const clientName = safeTypeName(options.name);
  const packageName = goPackageName(clientName);
  const clientRef = "modcdpclient.";
  const aliasObjectsName = `${clientName}AliasObjects`;
  const customCommandsName = `${clientName}CustomCommands`;
  const hasDefaultConfig = options.default_config != null;
  const statelessObjects = statelessAliasObjects(objects);
  const objectsByName = new Map(objects.map((object) => [object.name, object]));
  let out = `// Code generated by ModCDP codegen. DO NOT EDIT.\n`;
  out += `package ${packageName}\n\n`;
  out += `import (\n  "encoding/json"\n`;
  if (hasDefaultConfig) out += `  "os"\n`;
  out += `  modcdpclient "github.com/browserbase/modcdp/go/modcdp/client"\n`;
  out += `)\n\n`;
  out += emitGoSchemaDefinitions(objects);
  out += emitGoClientType(clientName, clientRef, aliasObjectsName, customCommandsName, sortedObjectsArray(objects), statelessObjects, options.default_config);
  for (const object of sortedObjectsArray(objects)) {
    const typeName = object.type_name || pascal(object.name);
    out += `type ${typeName} struct {\n`;
    out += `  alias ${clientRef}ModCDPAliasObject \`json:"-"\`\n`;
    out += emitGoSchemaFields(object.sticky_schema, typeName, new Set());
    out += `}\n\n`;
    out += emitGoAliasObjectConstructor(clientRef, object);
    for (const method of object.methods ?? []) {
      if (sdkPath(object, method).length === 2) out += emitGoMethod(clientRef, typeName, "receiver.alias.Client", "receiver.alias.Sticky", object, method, objectsByName);
    }
  }
  out += emitGoAliasObjectsFunction(clientRef, aliasObjectsName, sortedObjectsArray(objects));
  out += emitGoCustomCommandsFunction(clientRef, customCommandsName, commands);
  return out;
}

function emitGoClientType(clientName, clientRef, aliasObjectsName, customCommandsName, objects, statelessObjects, defaultConfig) {
  const concreteName = lowerFirst(clientName);
  const optionsName = `${clientName}Options`;
  const hasDefaultConfig = defaultConfig != null;
  let out = `type ${optionsName} ${clientRef}Config\n\n`;
  out += `type ${concreteName} struct {\n  *${clientRef}ModCDPClient\n`;
  for (const object of objects) {
    if (statelessObjects.has(object.name)) out += `  ${object.type_name || pascal(object.name)} ${object.type_name || pascal(object.name)} \`json:"-"\`\n`;
  }
  out += `}\n\n`;
  if (hasDefaultConfig) out += emitGoDefaultConfig(clientName, clientRef, defaultConfig);
  out += `func ${clientName}(options ...${optionsName}) *${concreteName} {\n`;
  out += `  config := ${clientRef}Config(${hasDefaultConfig ? `${clientName}DefaultOptions()` : `${optionsName}{}`})\n`;
  out += `  if len(options) > 0 {\n`;
  out += `    config = ${clientRef}Config(options[0])\n`;
  out += `  }\n`;
  out += `  generatedTypes := ${clientRef}CDPTypesConfig{\n`;
  out += `    CustomCommands: ${customCommandsName}(),\n`;
  out += `    CustomAliasObjects: ${aliasObjectsName}(),\n`;
  out += `  }\n`;
  out += `  if config.Types == nil {\n`;
  out += `    config.Types = &generatedTypes\n`;
  out += `  } else {\n`;
  out += `    config.Types.CustomCommands = append(config.Types.CustomCommands, generatedTypes.CustomCommands...)\n`;
  out += `    config.Types.CustomAliasObjects = append(config.Types.CustomAliasObjects, generatedTypes.CustomAliasObjects...)\n`;
  out += `  }\n`;
  out += `  receiver := &${concreteName}{ModCDPClient: ${clientRef}New(config)}\n`;
  for (const object of objects) {
    if (statelessObjects.has(object.name)) out += `  receiver.${object.type_name || pascal(object.name)} = new${object.type_name || pascal(object.name)}Alias(receiver.ModCDPClient, nil)\n`;
  }
  out += `  return receiver\n`;
  out += `}\n\n`;
  return out;
}

function emitGoDefaultConfig(clientName, clientRef, config) {
  return `const ${lowerFirst(clientName)}DefaultOptionsJSON = ${JSON.stringify(JSON.stringify(config))}\n\n` +
    `func ${clientName}DefaultOptions() ${clientName}Options {\n` +
    `  var config ${clientRef}Config\n` +
    `  if err := json.Unmarshal([]byte(os.ExpandEnv(${lowerFirst(clientName)}DefaultOptionsJSON)), &config); err != nil {\n` +
    `    panic(err)\n` +
    `  }\n` +
    `  return ${clientName}Options(config)\n` +
    `}\n\n`;
}

function emitGoSchemaDefinitions(objects) {
  const emitted = new Set(objects.map((object) => object.type_name || pascal(object.name)));
  let out = "";
  for (const object of sortedObjectsArray(objects)) {
    const defs = collectDefinitionsFromSchemas([object.sticky_schema, ...(object.methods ?? []).flatMap((method) => [method.params_schema, method.result_schema])]);
    for (const [name, schema] of sortedEntries(defs)) {
      const typeName = goExportName(name);
      if (emitted.has(typeName)) continue;
      emitted.add(typeName);
      out += emitGoSchemaDefinition(typeName, schema);
    }
  }
  return out;
}

function emitGoSchemaDefinition(name, schema) {
  if (Object.keys(schemaPropertiesObject(schema)).length > 0) return emitGoSchemaType(name, schema, new Set());
  let fieldType = goTypeForSchemaWithName(schema, name);
  if (fieldType === name || fieldType.startsWith(`*${name}`) || fieldType.startsWith(`[]${name}`)) fieldType = "json.RawMessage";
  return `type ${name} ${fieldType}\n\n`;
}

function emitGoAliasObjectConstructor(clientRef, object) {
  const typeName = object.type_name || pascal(object.name);
  let out = `func new${typeName}Alias(base *${clientRef}ModCDPClient, sticky ${clientRef}AliasSticky) ${typeName} {\n`;
  out += `  value := ${typeName}{alias: ${clientRef}NewModCDPAliasObject(base, sticky)}\n`;
  if (Object.keys(schemaPropertiesObject(object.sticky_schema)).length > 0) out += `  _ = value.applyAliasSticky(sticky)\n`;
  out += `  return value\n`;
  out += `}\n\n`;
  if (Object.keys(schemaPropertiesObject(object.sticky_schema)).length === 0) return out;
  out += `func (receiver *${typeName}) applyAliasSticky(sticky ${clientRef}AliasSticky) error {\n`;
  out += `  if sticky == nil {\n    return nil\n  }\n`;
  out += `  body, err := json.Marshal(sticky)\n`;
  out += `  if err != nil {\n    return err\n  }\n`;
  out += `  return json.Unmarshal(body, receiver)\n`;
  out += `}\n\n`;
  return out;
}

function emitGoMethod(clientRef, receiverType, clientExpression, stickyExpression, object, method, objectsByName) {
  const typeName = object.type_name || pascal(object.name);
  const methodName = goExportName(method.name);
  const paramsType = `${typeName}${methodName}Params`;
  const resultType = `${typeName}${methodName}Result`;
  const optionalFields = receiverStickyParamFields(object, method);
  const paramsOptional = paramsCanBeOmitted(method.params_schema, optionalFields);
  const paramsSignature = paramsOptional ? `params ...${paramsType}` : `params ${paramsType}`;
  const paramsValue = paramsOptional ? "request" : "params";
  let out = emitGoSchemaType(paramsType, method.params_schema, optionalFields);
  out += emitGoSchemaType(resultType, method.result_schema, new Set());
  const stickyParam = JSON.stringify(method.sticky_param || "");
  const stickyParams = goStringSliceLiteral(method.sticky_params || []);
  const stickyFields = goStringSliceLiteral(method.sticky_fields || []);
  const unwrap = method.return?.unwrap || "";
  const returnObject = method.return?.object || "";
  const optionalResolver = (zeroValue) =>
    paramsOptional
      ? `  request, err := ${clientRef}OptionalAliasParams(${JSON.stringify(`${object.name}.${method.name}`)}, params)\n  if err != nil {\n    return ${zeroValue}, err\n  }\n`
      : "";
  if (returnObject) {
    const target = objectsByName.get(returnObject);
    if (!target) throw new Error(`${object.name}.${method.name} returns unknown alias object ${returnObject}`);
    const targetType = target.type_name || pascal(target.name);
    if (!method.command) {
      out += `func (receiver ${receiverType}) ${methodName}(${paramsSignature}) (${targetType}, error) {\n`;
      out += optionalResolver(`${targetType}{}`);
      out += `  return new${targetType}Alias(${clientExpression}, nil), nil\n`;
      out += `}\n\n`;
      return out;
    }
    if (method.return?.array) {
      out += `func (receiver ${receiverType}) ${methodName}(${paramsSignature}) ([]${targetType}, error) {\n`;
      out += optionalResolver("nil");
      out += `  raw, err := ${clientRef}SendAliasCommandWithStickyParams[json.RawMessage](${clientExpression}, ${JSON.stringify(method.command)}, ${paramsValue}, ${stickyExpression}, ${stickyParam}, ${stickyParams}, ${stickyFields}, "")\n`;
      out += `  if err != nil {\n    return nil, err\n  }\n`;
      out += `  items, err := ${clientRef}AliasArrayFromResult(raw, ${JSON.stringify(unwrap)})\n`;
      out += `  if err != nil {\n    return nil, err\n  }\n`;
      out += `  output := make([]${targetType}, 0, len(items))\n`;
      out += `  for _, item := range items {\n`;
      out += `    sticky, err := ${clientRef}AliasStickyFromResult(item, "", ${goStringSliceLiteral(target.sticky_fields || [])})\n`;
      out += `    if err != nil {\n      return nil, err\n    }\n`;
      out += `    output = append(output, new${targetType}Alias(${clientExpression}, sticky))\n`;
      out += `  }\n`;
      out += `  return output, nil\n`;
      out += `}\n\n`;
      return out;
    }
    if (method.return?.nullable) {
      out += `func (receiver ${receiverType}) ${methodName}(${paramsSignature}) (*${targetType}, error) {\n`;
      out += optionalResolver("nil");
      out += `  raw, err := ${clientRef}SendAliasCommandWithStickyParams[json.RawMessage](${clientExpression}, ${JSON.stringify(method.command)}, ${paramsValue}, ${stickyExpression}, ${stickyParam}, ${stickyParams}, ${stickyFields}, "")\n`;
      out += `  if err != nil {\n    return nil, err\n  }\n`;
      out += `  unwrapped, err := ${clientRef}UnwrapAliasResult(raw, ${JSON.stringify(unwrap)})\n`;
      out += `  if err != nil {\n    return nil, err\n  }\n`;
      out += `  if unwrapped == nil {\n    return nil, nil\n  }\n`;
      out += `  sticky, err := ${clientRef}AliasStickyFromResult(unwrapped, "", ${goStringSliceLiteral(target.sticky_fields || [])})\n`;
      out += `  if err != nil {\n    return nil, err\n  }\n`;
      out += `  value := new${targetType}Alias(${clientExpression}, sticky)\n`;
      out += `  return &value, nil\n`;
      out += `}\n\n`;
      return out;
    }
    out += `func (receiver ${receiverType}) ${methodName}(${paramsSignature}) (${targetType}, error) {\n`;
    out += optionalResolver(`${targetType}{}`);
    out += `  raw, err := ${clientRef}SendAliasCommandWithStickyParams[${clientRef}AliasJSONObject](${clientExpression}, ${JSON.stringify(method.command)}, ${paramsValue}, ${stickyExpression}, ${stickyParam}, ${stickyParams}, ${stickyFields}, "")\n`;
    out += `  if err != nil {\n    return ${targetType}{}, err\n  }\n`;
    out += `  sticky, err := ${clientRef}AliasStickyFromResult(raw, ${JSON.stringify(unwrap)}, ${goStringSliceLiteral(target.sticky_fields || [])})\n`;
    out += `  if err != nil {\n    return ${targetType}{}, err\n  }\n`;
    out += `  return new${targetType}Alias(${clientExpression}, sticky), nil\n`;
    out += `}\n\n`;
    return out;
  }
  out += `func (receiver ${receiverType}) ${methodName}(${paramsSignature}) (${resultType}, error) {\n`;
  out += optionalResolver(`${resultType}{}`);
  out += `  return ${clientRef}SendAliasCommandWithStickyParams[${resultType}](${clientExpression}, ${JSON.stringify(method.command)}, ${paramsValue}, ${stickyExpression}, ${stickyParam}, ${stickyParams}, ${stickyFields}, ${JSON.stringify(unwrap)})\n`;
  out += `}\n\n`;
  return out;
}


function emitGoSchemaType(name, schema, optionalFields) {
  let out = emitGoInlineSchemaTypes(name, schema, new Set([name]));
  out += `type ${name} struct {\n`;
  out += emitGoSchemaFields(schema, name, optionalFields);
  out += `}\n\n`;
  return out;
}

function emitGoInlineSchemaTypes(parentName, schema, emitted) {
  let out = "";
  for (const [property, propertySchema] of sortedEntries(schemaPropertiesObject(schema))) {
    out += emitGoInlineSchemaTypeForSchema(`${parentName}${goExportName(property)}`, propertySchema, emitted);
  }
  return out;
}

function emitGoInlineSchemaTypeForSchema(name, schema, emitted) {
  if (!schema || typeof schema !== "object" || schema.$ref) return "";
  const nonNull = nullableSchema(schema);
  if (nonNull) return emitGoInlineSchemaTypeForSchema(name, nonNull, emitted);
  if (schema.type === "array") return emitGoInlineSchemaTypeForSchema(`${name}Item`, schema.items, emitted);
  let out = "";
  if (schema.additionalProperties && typeof schema.additionalProperties === "object") {
    out += emitGoInlineSchemaTypeForSchema(`${name}Value`, schema.additionalProperties, emitted);
  }
  if (Object.keys(schemaPropertiesObject(schema)).length === 0 || emitted.has(name)) return out;
  emitted.add(name);
  out += emitGoInlineSchemaTypes(name, schema, emitted);
  out += `type ${name} struct {\n`;
  out += emitGoSchemaFields(schema, name, new Set());
  out += `}\n\n`;
  return out;
}

function emitGoSchemaFields(schema, parentName, optionalFields) {
  let out = "";
  const properties = schemaPropertiesObject(schema);
  const required = requiredSet(schema);
  for (const [property, propertySchema] of sortedEntries(properties)) {
    const receiverStickyOptional = optionalFields.has(property);
    if (receiverStickyOptional) required.delete(property);
    let fieldType = goTypeForSchemaWithName(propertySchema, `${parentName}${goExportName(property)}`);
    if (!required.has(property) && !receiverStickyOptional && goIsObjectLikeSchema(propertySchema)) fieldType = goPointerType(fieldType);
    let tag = property;
    if (!required.has(property)) tag += ",omitempty";
    out += `  ${goExportName(property)} ${fieldType} \`json:"${tag}"\`\n`;
  }
  return out;
}

function goTypeForSchemaWithName(schema, suggestedName) {
  if (!schema || typeof schema !== "object") return "json.RawMessage";
  if (schema.$ref) return goTypeNameForRef(schema.$ref);
  const union = unionSchemas(schema);
  if (union) {
    let nullable = false;
    const nonNullTypes = [];
    for (const item of union) {
      if (item?.type === "null") {
        nullable = true;
        continue;
      }
      const itemType = goTypeForSchemaWithName(item, suggestedName);
      if (!nonNullTypes.includes(itemType)) nonNullTypes.push(itemType);
    }
    if (nonNullTypes.length > 0) {
      let nonNullType = nonNullTypes[0];
      if (nonNullTypes.length > 1) {
        nonNullType = nonNullTypes.includes("int") && nonNullTypes.includes("float64") && nonNullTypes.length === 2 ? "float64" : "json.RawMessage";
      }
      if (nullable) return nonNullType === "string" ? nonNullType : goPointerType(nonNullType);
      return nonNullType;
    }
  }
  if (Array.isArray(schema.type)) {
    const nonNull = schema.type.find((item) => item !== "null");
    if (typeof nonNull === "string") {
      const scalar = goScalarType(nonNull, schema, suggestedName);
      return scalar === "string" ? scalar : goPointerType(scalar);
    }
  }
  if (typeof schema.type === "string") return goScalarType(schema.type, schema, suggestedName);
  if (schema.properties) return suggestedName;
  return "json.RawMessage";
}

function goScalarType(value, schema, suggestedName) {
  if (value === "string") return "string";
  if (value === "boolean") return "bool";
  if (value === "integer") return "int";
  if (value === "number") return "float64";
  if (value === "object") {
    if (Object.keys(schemaPropertiesObject(schema)).length > 0) return suggestedName;
    if (schema.additionalProperties && typeof schema.additionalProperties === "object") {
      return `map[string]${goTypeForSchemaWithName(schema.additionalProperties, `${suggestedName}Value`).replace(/^\*/, "")}`;
    }
    return "json.RawMessage";
  }
  if (value === "array") {
    if (schema.items && typeof schema.items === "object") return `[]${goTypeForSchemaWithName(schema.items, `${suggestedName}Item`).replace(/^\*/, "")}`;
    return "[]json.RawMessage";
  }
  return "json.RawMessage";
}

function nullableSchema(schema) {
  const union = unionSchemas(schema);
  if (!union) return null;
  let nonNull = null;
  let nullable = false;
  for (const item of union) {
    if (item?.type === "null") nullable = true;
    else if (nonNull == null) nonNull = item;
  }
  return nullable ? nonNull : null;
}

function goIsObjectLikeSchema(schema) {
  if (!schema || typeof schema !== "object") return false;
  if (schema.$ref) return true;
  if (schema.type === "object" || schema.properties) return true;
  const nonNull = nullableSchema(schema);
  return nonNull ? goIsObjectLikeSchema(nonNull) : false;
}

function goPointerType(value) {
  if (value === "any" || value.startsWith("*") || value.startsWith("[]")) return value;
  return `*${value}`;
}

function goTypeNameForRef(ref) {
  const prefix = "#/$defs/";
  return String(ref).startsWith(prefix) ? goExportName(String(ref).slice(prefix.length)) : "json.RawMessage";
}

function emitGoAliasObjectsFunction(clientRef, name, objects) {
  return `func ${name}() []${clientRef}CustomAliasObject {\n  var values []${clientRef}CustomAliasObject\n  if err := json.Unmarshal([]byte(${JSON.stringify(JSON.stringify(sanitizeRegistry(objects)))}), &values); err != nil {\n    panic(err)\n  }\n  return values\n}\n\n`;
}

function emitGoCustomCommandsFunction(clientRef, name, commands) {
  return `func ${name}() []${clientRef}CustomCommand {\n  var values []${clientRef}CustomCommand\n  if err := json.Unmarshal([]byte(${JSON.stringify(JSON.stringify(sanitizeCommandRegistry(commands)))}), &values); err != nil {\n    panic(err)\n  }\n  return values\n}\n\n`;
}


function collectDefinitionsFromSchemas(schemas) {
  const defs = new Map();
  for (const schema of schemas) collectSchemaDefinitions(schema, defs);
  return defs;
}

function sortedObjectsArray(objects) {
  return [...objects].sort((left, right) => String(left.name).localeCompare(String(right.name)));
}

function goStringSliceLiteral(values) {
  if (!values || values.length === 0) return "nil";
  return `[]string{${values.map((value) => JSON.stringify(value)).join(", ")}}`;
}

function goExportName(value) {
  return pascal(value);
}

function goPackageName(value) {
  return String(value).replace(/[^A-Za-z0-9]/g, "").toLowerCase() || "generatedclient";
}


if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const manifest = JSON.parse(readFileSync("testdata/codegen/stagehand_alias_manifest.json", "utf8"));
  const output = "testdata/codegen/stagehand_client_generated_go/stagehand_client_gen.go";
  const generated = generateClientWithAliasesForGo({
    language: "go",
    name: "StagehandClient",
    custom_commands: manifest.custom_commands,
    custom_alias_objects: manifest.custom_alias_objects,
    default_config: manifest.modcdp_config,
    output,
  }, manifest.custom_alias_objects ?? [], manifest.custom_commands ?? []);
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, generated);
}
