import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { pathToFileURL } from "node:url";

import type { GenerateClientWithAliasesOptions } from "./codegen.ts";
import {
  collectDefinitions,
  lowerFirst,
  paramsCanBeOmitted,
  pascal,
  receiverStickyParamFields,
  refName,
  requiredSet,
  safeTypeName,
  sanitizeCommandRegistry,
  sanitizeRegistry,
  schemaProperties,
  schemaPropertiesObject,
  sdkMethodName,
  sdkPath,
  sortedEntries,
  statelessAliasObjects,
  unionSchemas,
} from "./codegen_shared.ts";

export { generateClientWithAliasesForTs };

function generateClientWithAliasesForTs(options: GenerateClientWithAliasesOptions, objects, commands) {
  const clientName = safeTypeName(options.name);
  const functionPrefix = lowerFirst(clientName);
  const objectNames = new Set(objects.map((object) => object.type_name || pascal(object.name)));
  const statelessObjects = statelessAliasObjects(objects);
  const defs = collectDefinitions(objects);
  const hasDefaultConfig = options.default_config != null;
  let out = `// Code generated by ModCDP codegen. DO NOT EDIT.\n`;
  out += `import { ModCDPClient } from "../../src/client/ModCDPClient.js";\n`;
  out += `import { CDPTypes, type CDPTypesConfig } from "../../src/types/CDPTypes.js";\n`;
  out += `import type { ModCDPAddCustomCommandParams, ModCDPAliasObject as ModCDPAliasObjectRegistration } from "../../src/types/modcdp.js";\n`;
  out += `import { ModCDPAliasObject, aliasArrayFromResult, aliasStickyFromResult, optionalAliasParams, sendAliasCommandWithStickyParams } from "../../src/client/alias.js";\n\n`;
  out += `export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n\n`;
  out += `export type ${clientName}Options = ConstructorParameters<typeof ModCDPClient>[0];\n\n`;
  if (hasDefaultConfig) out += emitTSDefaultConfig(clientName, functionPrefix, options.default_config);
  for (const [name, schema] of sortedEntries(defs)) out += emitTSInterface(name, schema, objectNames);
  for (const object of objects) {
    const typeName = object.type_name || pascal(object.name);
    if (schemaProperties(object.sticky_schema).size > 0)
      out += emitTSInterface(`${typeName}Data`, object.sticky_schema, objectNames);
  }
  for (const object of objects) {
    const typeName = object.type_name || pascal(object.name);
    for (const method of object.methods ?? []) {
      out += emitTSInterface(
        `${typeName}${pascal(method.name)}Params`,
        method.params_schema,
        objectNames,
        receiverStickyParamFields(object, method),
      );
      out += emitTSInterface(`${typeName}${pascal(method.name)}Result`, method.result_schema, objectNames);
    }
  }
  out += `export class ${clientName} extends ModCDPClient {\n`;
  for (const object of objects) {
    if (!statelessObjects.has(object.name)) continue;
    const property = sdkPath(object, object.methods?.[0] ?? null)[0] ?? object.name;
    out += `  readonly ${property}: ${object.type_name || pascal(object.name)};\n`;
  }
  out += `  constructor(config: ${clientName}Options = ${hasDefaultConfig ? `${functionPrefix}DefaultOptions()` : "{}"}) {\n`;
  out += `    const generatedTypes = ${functionPrefix}Types();\n`;
  out += `    const types = config.types instanceof CDPTypes ? config.types.update(generatedTypes) : new CDPTypes(config.types ?? {}).update(generatedTypes);\n`;
  out += `    super({ ...config, types });\n`;
  for (const object of objects) {
    if (!statelessObjects.has(object.name)) continue;
    const property = sdkPath(object, object.methods?.[0] ?? null)[0] ?? object.name;
    out += `    this.${property} = new ${object.type_name || pascal(object.name)}(this, {});\n`;
  }
  out += `  }\n`;
  out += `}\n\n`;
  for (const object of objects) out += emitTSClass(object, objects);
  out += `export function ${functionPrefix}Types(): CDPTypesConfig {\n  return {\n    custom_commands: ${functionPrefix}CustomCommands(),\n    custom_alias_objects: ${functionPrefix}AliasObjects(),\n  };\n}\n\n`;
  out += `export function ${functionPrefix}CustomCommands(): ModCDPAddCustomCommandParams[] {\n  return ${JSON.stringify(sanitizeCommandRegistry(commands), null, 2)} as ModCDPAddCustomCommandParams[];\n}\n\n`;
  out += `export function ${functionPrefix}AliasObjects(): ModCDPAliasObjectRegistration[] {\n  return ${JSON.stringify(sanitizeRegistry(objects), null, 2)} as ModCDPAliasObjectRegistration[];\n}\n`;
  return out;
}

function emitTSDefaultConfig(clientName, functionPrefix, config) {
  return (
    `const ${clientName.toUpperCase()}_DEFAULT_OPTIONS_JSON = ${JSON.stringify(JSON.stringify(config))};\n\n` +
    `export function ${functionPrefix}DefaultOptions(): ${clientName}Options {\n` +
    `  return ${functionPrefix}ReplaceEnv(JSON.parse(${clientName.toUpperCase()}_DEFAULT_OPTIONS_JSON)) as ${clientName}Options;\n` +
    `}\n\n` +
    `function ${functionPrefix}ReplaceEnv(value: unknown): unknown {\n` +
    `  if (typeof value === "string") return value.replaceAll("\${CHROME_PATH}", process.env.CHROME_PATH ?? "").replaceAll("\${STAGEHAND_EXTENSION_PATH}", process.env.STAGEHAND_EXTENSION_PATH ?? "");\n` +
    `  if (Array.isArray(value)) return value.map((item) => ${functionPrefix}ReplaceEnv(item));\n` +
    `  if (value != null && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, ${functionPrefix}ReplaceEnv(item)]));\n` +
    `  return value;\n` +
    `}\n\n`
  );
}

function emitTSClass(object, objects) {
  const typeName = object.type_name || pascal(object.name);
  const stickyType = schemaProperties(object.sticky_schema).size > 0 ? `${typeName}Data` : "Record<string, never>";
  let out = `export class ${typeName} extends ModCDPAliasObject${stickyType === "Record<string, never>" ? "" : ` implements ${stickyType}`} {\n`;
  for (const [name, schema] of sortedEntries(schemaPropertiesObject(object.sticky_schema))) {
    out += `  ${tsFieldName(name)}?: ${tsType(schema, `${typeName}${pascal(name)}`, new Set(objects.map((item) => item.type_name || pascal(item.name))))} | null;\n`;
  }
  out += `  constructor(client: ModCDPClient, sticky: Partial<${stickyType}> = {}) {\n    super(client, sticky as Record<string, unknown>);\n    Object.assign(this, sticky);\n  }\n`;
  for (const method of object.methods ?? []) {
    if (sdkPath(object, method).length === 2) out += emitTSMethod(object, method, objects);
  }
  out += `}\n\n`;
  return out;
}

function emitTSMethod(object, method, objects, receiver = { client: "this.client", sticky: "this.sticky" }) {
  const typeName = object.type_name || pascal(object.name);
  const methodName = sdkMethodName(object, method);
  const paramsType = `${typeName}${pascal(method.name)}Params`;
  const resultType = `${typeName}${pascal(method.name)}Result`;
  const optional = paramsCanBeOmitted(method.params_schema, receiverStickyParamFields(object, method));
  const signature = optional ? `...params: ${paramsType}[]` : `params: ${paramsType}`;
  const paramsValue = optional ? `optionalAliasParams("${object.name}.${method.name}", params)` : "params";
  const stickyParam = JSON.stringify(method.sticky_param || "");
  const stickyParams = JSON.stringify(method.sticky_params || []);
  const stickyFields = JSON.stringify(method.sticky_fields || []);
  if (method.return?.object) {
    const target = objects.find((item) => item.name === method.return.object);
    const targetType = target?.type_name || pascal(method.return.object);
    const targetStickyFields = JSON.stringify(target?.sticky_fields || []);
    if (method.return.array) {
      return `  async ${methodName}(${signature}): Promise<${targetType}[]> {\n    const request = ${paramsValue};\n    const raw = await sendAliasCommandWithStickyParams<JsonValue>(${receiver.client}, ${JSON.stringify(method.command)}, request, ${receiver.sticky}, ${stickyParam}, ${stickyParams}, ${stickyFields}, "");\n    return aliasArrayFromResult(raw, ${JSON.stringify(method.return.unwrap || "")}).map((item) => new ${targetType}(${receiver.client}, aliasStickyFromResult(item, "", ${targetStickyFields})));\n  }\n`;
    }
    if (method.return.nullable) {
      return `  async ${methodName}(${signature}): Promise<${targetType} | null> {\n    const request = ${paramsValue};\n    const raw = await sendAliasCommandWithStickyParams<JsonValue>(${receiver.client}, ${JSON.stringify(method.command)}, request, ${receiver.sticky}, ${stickyParam}, ${stickyParams}, ${stickyFields}, "");\n    const unwrapped = aliasStickyFromResult(raw, ${JSON.stringify(method.return.unwrap || "")}, ${targetStickyFields});\n    return Object.keys(unwrapped).length === 0 ? null : new ${targetType}(${receiver.client}, unwrapped);\n  }\n`;
    }
    return `  async ${methodName}(${signature}): Promise<${targetType}> {\n    const request = ${paramsValue};\n    const raw = await sendAliasCommandWithStickyParams<JsonValue>(${receiver.client}, ${JSON.stringify(method.command)}, request, ${receiver.sticky}, ${stickyParam}, ${stickyParams}, ${stickyFields}, "");\n    return new ${targetType}(${receiver.client}, aliasStickyFromResult(raw, ${JSON.stringify(method.return.unwrap || "")}, ${targetStickyFields}));\n  }\n`;
  }
  return `  async ${methodName}(${signature}): Promise<${resultType}> {\n    const request = ${paramsValue};\n    return sendAliasCommandWithStickyParams<${resultType}>(${receiver.client}, ${JSON.stringify(method.command)}, request, ${receiver.sticky}, ${stickyParam}, ${stickyParams}, ${stickyFields}, ${JSON.stringify(method.return?.unwrap || "")});\n  }\n`;
}

function emitTSInterface(name, schema, objectNames, optionalFields = new Set()) {
  const properties = schemaPropertiesObject(schema);
  if (Object.keys(properties).length === 0) return `export type ${name} = Record<string, JsonValue>;\n\n`;
  const required = requiredSet(schema);
  let out = `export interface ${name} {\n`;
  for (const [property, propertySchema] of sortedEntries(properties)) {
    const optional = !required.has(property) || optionalFields.has(property);
    out += `  ${tsFieldName(property)}${optional ? "?" : ""}: ${tsType(propertySchema, `${name}${pascal(property)}`, objectNames)}${optional ? " | null" : ""};\n`;
  }
  out += `}\n\n`;
  return out;
}

function tsType(schema, suggestedName, objectNames) {
  if (!schema || typeof schema !== "object") return "JsonValue";
  if (schema.$ref) {
    const ref = refName(schema.$ref);
    return objectNames.has(ref) ? `${ref}Data` : ref;
  }
  const union = unionSchemas(schema);
  if (union) {
    const parts = union.filter((item) => item.type !== "null").map((item) => tsType(item, suggestedName, objectNames));
    return [...new Set(parts.length ? parts : ["null"])].join(" | ");
  }
  if (schema.type === "array") {
    const itemType = tsType(schema.items, `${suggestedName}Item`, objectNames);
    return itemType.includes(" | ") ? `(${itemType})[]` : `${itemType}[]`;
  }
  if (schema.type === "object" || schema.properties) {
    if (schema.properties) return tsInlineObjectType(schema, objectNames);
    return "{ [key: string]: JsonValue }";
  }
  if (Array.isArray(schema.type))
    return schema.type
      .filter((item) => item !== "null")
      .map((item) => tsType({ type: item }, suggestedName, objectNames))
      .join(" | ");
  if (schema.enum) return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  if (schema.type === "string") return "string";
  if (schema.type === "boolean") return "boolean";
  if (schema.type === "integer" || schema.type === "number") return "number";
  return "JsonValue";
}

function tsInlineObjectType(schema, objectNames) {
  const properties = schemaPropertiesObject(schema);
  const required = requiredSet(schema);
  const fields = sortedEntries(properties).map(([property, propertySchema]) => {
    const optional = !required.has(property);
    return `${tsFieldName(property)}${optional ? "?" : ""}: ${tsType(propertySchema, `${pascal(property)}`, objectNames)}${optional ? " | null" : ""}`;
  });
  return `{ ${fields.join("; ")} }`;
}

function tsFieldName(name) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const manifest = JSON.parse(readFileSync("testdata/codegen/stagehand_alias_manifest.json", "utf8"));
  const output = "js/test/stagehand_client_generated/stagehand_client_gen.ts";
  const generated = generateClientWithAliasesForTs(
    {
      language: "ts",
      name: "StagehandClient",
      custom_commands: manifest.custom_commands,
      custom_alias_objects: manifest.custom_alias_objects,
      default_config: manifest.modcdp_config,
      output,
    },
    manifest.custom_alias_objects ?? [],
    manifest.custom_commands ?? [],
  );
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, generated);
}
