import { readFileSync } from "node:fs";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { pathToFileURL } from "node:url";

import type { GenerateClientWithAliasesOptions } from "./codegen.ts";
import {
  collectDefinitions,
  paramsCanBeOmitted,
  pascal,
  receiverStickyParamFields,
  refName,
  requiredSet,
  safeTypeName,
  sanitizeCommandRegistry,
  sanitizeRegistry,
  schemaPropertiesObject,
  sdkMethodName,
  sdkPath,
  sortedEntries,
  statelessAliasObjects,
  unionSchemas,
} from "./codegen_shared.ts";

export { generateClientWithAliasesForPython };

function generateClientWithAliasesForPython(options: GenerateClientWithAliasesOptions, objects, commands) {
  const clientName = safeTypeName(options.name);
  const functionPrefix = pyFieldName(clientName);
  const objectNames = new Set(objects.map((object) => object.type_name || pascal(object.name)));
  const statelessObjects = statelessAliasObjects(objects);
  const defs = collectDefinitions(objects);
  const hasDefaultConfig = options.default_config != null;
  let out = `# Code generated by ModCDP codegen. DO NOT EDIT.\nfrom __future__ import annotations\n\nimport json\nimport os\nfrom collections.abc import Mapping\nfrom typing import Any, cast\nfrom pydantic import AliasChoices, BaseModel, ConfigDict, Field, PrivateAttr\n\nfrom modcdp import ModCDPClient\nfrom modcdp.client.alias import ModCDPAliasObject, alias_array_from_result, alias_sticky_from_result, optional_alias_params, send_alias_command_with_sticky_params\nfrom modcdp.types.CDPTypes import CDPTypes\n\nJsonValue = Any\n\nclass AliasModel(BaseModel):\n    model_config = ConfigDict(extra="forbid", populate_by_name=True, arbitrary_types_allowed=True)\n\n    def alias_params(self) -> dict[str, object]:\n        return cast(dict[str, object], self.model_dump(mode="json", exclude_none=True, by_alias=True))\n\n`;
  if (hasDefaultConfig) out += emitPythonDefaultConfig(functionPrefix, options.default_config);
  for (const [name, schema] of sortedEntries(defs)) {
    if (!objectNames.has(name)) out += emitPyModel(name, schema, objectNames);
  }
  for (const object of objects) {
    const typeName = object.type_name || pascal(object.name);
    for (const method of object.methods ?? []) {
      out += emitPyModel(
        `${typeName}${pascal(method.name)}Params`,
        method.params_schema,
        objectNames,
        receiverStickyParamFields(object, method),
      );
      out += emitPyModel(`${typeName}${pascal(method.name)}Result`, method.result_schema, objectNames);
    }
  }
  out += `class ${clientName}(ModCDPClient):\n`;
  for (const object of objects) {
    if (!statelessObjects.has(object.name)) continue;
    const property = sdkPath(object, object.methods?.[0] ?? null)[0] ?? object.name;
    out += `    ${pyFieldName(property)}: ${object.type_name || pascal(object.name)}\n`;
  }
  out += `\n    def __init__(self, config: Mapping[str, Any] | None = None, **kwargs: Any) -> None:\n        payload: dict[str, Any] = {**dict(${hasDefaultConfig ? `${functionPrefix}_default_options()` : "{}"} if config is None else config), **kwargs}\n        generated_types = ${functionPrefix}_types()\n        existing_types = payload.get("types")\n        if isinstance(existing_types, CDPTypes):\n            payload["types"] = existing_types.update(generated_types)\n        elif isinstance(existing_types, Mapping):\n            payload["types"] = CDPTypes(existing_types).update(generated_types)\n        else:\n            payload["types"] = CDPTypes(generated_types)\n        super().__init__(**payload)\n`;
  for (const object of objects) {
    if (!statelessObjects.has(object.name)) continue;
    const property = sdkPath(object, object.methods?.[0] ?? null)[0] ?? object.name;
    out += `        self.${pyFieldName(property)} = ${object.type_name || pascal(object.name)}(self, {})\n`;
  }
  out += `\n`;
  for (const object of objects) out += emitPyClass(object, objects);
  out += `for _model in list(AliasModel.__subclasses__()):\n    _model.model_rebuild()\n\n`;
  out += `def ${functionPrefix}_types() -> dict[str, object]:\n    return {\n        "custom_commands": ${functionPrefix}_custom_commands(),\n        "custom_alias_objects": ${functionPrefix}_alias_objects(),\n    }\n\n`;
  out += `def ${functionPrefix}_custom_commands() -> list[dict[str, object]]:\n    return ${pyLiteral(sanitizeCommandRegistry(commands))}\n\n`;
  out += `def ${functionPrefix}_alias_objects() -> list[dict[str, object]]:\n    return ${pyLiteral(sanitizeRegistry(objects))}\n`;
  return out;
}

function emitPythonDefaultConfig(functionPrefix, config) {
  return (
    `${functionPrefix.toUpperCase()}_DEFAULT_OPTIONS_JSON = ${JSON.stringify(JSON.stringify(config))}\n\n` +
    `def ${functionPrefix}_default_options() -> dict[str, Any]:\n` +
    `    return cast(dict[str, Any], _${functionPrefix}_replace_env(json.loads(${functionPrefix.toUpperCase()}_DEFAULT_OPTIONS_JSON)))\n\n` +
    `def _${functionPrefix}_replace_env(value: object) -> object:\n` +
    `    if isinstance(value, str):\n` +
    `        return value.replace("\${CHROME_PATH}", os.environ.get("CHROME_PATH", "")).replace("\${STAGEHAND_EXTENSION_PATH}", os.environ.get("STAGEHAND_EXTENSION_PATH", ""))\n` +
    `    if isinstance(value, list):\n` +
    `        return [_${functionPrefix}_replace_env(item) for item in value]\n` +
    `    if isinstance(value, dict):\n` +
    `        return {key: _${functionPrefix}_replace_env(item) for key, item in value.items()}\n` +
    `    return value\n\n`
  );
}

function emitPyClass(object, objects) {
  const typeName = object.type_name || pascal(object.name);
  let out = `class ${typeName}(AliasModel, ModCDPAliasObject):\n    _client: ModCDPClient | None = PrivateAttr(default=None)\n    _sticky: dict[str, object] = PrivateAttr(default_factory=dict)\n`;
  for (const [name, schema] of sortedEntries(schemaPropertiesObject(object.sticky_schema))) {
    out += `    ${pyFieldName(name)}: ${pyType(schema, `${typeName}${pascal(name)}`, new Set(objects.map((item) => item.type_name || pascal(item.name))))} | None = ${pyFieldDefault(name)}\n`;
  }
  out += `\n    def __init__(self, client: ModCDPClient | None = None, sticky: dict[str, object] | None = None, **data: object) -> None:\n        payload = {**(sticky or {}), **data}\n        AliasModel.__init__(self, **payload)\n        self._client = client\n        self._sticky = self.alias_params()\n\n    @property\n    def client(self) -> ModCDPClient:\n        if self._client is None:\n            raise RuntimeError("${typeName} is not bound to a ModCDPClient")\n        return self._client\n\n    @property\n    def sticky(self) -> dict[str, object]:\n        return dict(self._sticky)\n`;
  for (const method of object.methods ?? []) {
    if (sdkPath(object, method).length === 2) out += emitPyMethod(object, method, objects);
  }
  return `${out}\n`;
}

function emitPyMethod(object, method, objects, receiver = { client: "self.client", sticky: "self.sticky" }) {
  const typeName = object.type_name || pascal(object.name);
  const methodName = sdkMethodName(object, method);
  const paramsType = `${typeName}${pascal(method.name)}Params`;
  const resultType = `${typeName}${pascal(method.name)}Result`;
  const optional = paramsCanBeOmitted(method.params_schema, receiverStickyParamFields(object, method));
  const signature = optional ? `self, *params: ${paramsType}` : `self, params: ${paramsType}`;
  const request = optional ? `optional_alias_params("${object.name}.${method.name}", params)` : "params";
  const stickyParam = JSON.stringify(method.sticky_param || "");
  const stickyParams = pyLiteral(method.sticky_params || []);
  const stickyFields = pyLiteral(method.sticky_fields || []);
  if (method.return?.object) {
    const target = objects.find((item) => item.name === method.return.object);
    const targetType = target?.type_name || pascal(method.return.object);
    const targetStickyFields = pyLiteral(target?.sticky_fields || []);
    if (method.return.array) {
      return `\n    def ${methodName}(${signature}) -> list[${targetType}]:\n        request = ${request}\n        raw = send_alias_command_with_sticky_params(${receiver.client}, ${JSON.stringify(method.command)}, request, ${receiver.sticky}, ${stickyParam}, ${stickyParams}, ${stickyFields}, "")\n        return [${targetType}(${receiver.client}, alias_sticky_from_result(item, "", ${targetStickyFields})) for item in alias_array_from_result(raw, ${JSON.stringify(method.return.unwrap || "")})]\n`;
    }
    if (method.return.nullable) {
      return `\n    def ${methodName}(${signature}) -> ${targetType} | None:\n        request = ${request}\n        raw = send_alias_command_with_sticky_params(${receiver.client}, ${JSON.stringify(method.command)}, request, ${receiver.sticky}, ${stickyParam}, ${stickyParams}, ${stickyFields}, "")\n        sticky = alias_sticky_from_result(raw, ${JSON.stringify(method.return.unwrap || "")}, ${targetStickyFields})\n        return None if not sticky else ${targetType}(${receiver.client}, sticky)\n`;
    }
    return `\n    def ${methodName}(${signature}) -> ${targetType}:\n        request = ${request}\n        raw = send_alias_command_with_sticky_params(${receiver.client}, ${JSON.stringify(method.command)}, request, ${receiver.sticky}, ${stickyParam}, ${stickyParams}, ${stickyFields}, "")\n        return ${targetType}(${receiver.client}, alias_sticky_from_result(raw, ${JSON.stringify(method.return.unwrap || "")}, ${targetStickyFields}))\n`;
  }
  return `\n    def ${methodName}(${signature}) -> ${resultType}:\n        request = ${request}\n        raw = send_alias_command_with_sticky_params(${receiver.client}, ${JSON.stringify(method.command)}, request, ${receiver.sticky}, ${stickyParam}, ${stickyParams}, ${stickyFields}, ${JSON.stringify(method.return?.unwrap || "")})\n        return ${resultType}.model_validate(raw if isinstance(raw, dict) else {"value": raw})\n`;
}

function emitPyModel(name, schema, objectNames, optionalFields = new Set()) {
  const properties = schemaPropertiesObject(schema);
  if (Object.keys(properties).length === 0) return `class ${name}(AliasModel):\n    pass\n\n`;
  const required = requiredSet(schema);
  let out = `class ${name}(AliasModel):\n`;
  for (const [property, propertySchema] of sortedEntries(properties)) {
    const optional = !required.has(property) || optionalFields.has(property);
    out += `    ${pyFieldName(property)}: ${pyType(propertySchema, `${name}${pascal(property)}`, objectNames)}${optional ? " | None" : ""} = ${optional ? pyFieldDefault(property) : pyRequiredFieldDefault(property)}\n`;
  }
  return `${out}\n`;
}

function pyType(schema, suggestedName, objectNames) {
  if (!schema || typeof schema !== "object") return "JsonValue";
  if (schema.$ref) {
    const ref = refName(schema.$ref);
    return ref;
  }
  const union = unionSchemas(schema);
  if (union) {
    const parts = union.filter((item) => item.type !== "null").map((item) => pyType(item, suggestedName, objectNames));
    return [...new Set(parts.length ? parts : ["None"])].join(" | ");
  }
  if (schema.type === "array") return `list[${pyType(schema.items, `${suggestedName}Item`, objectNames)}]`;
  if (schema.type === "object" || schema.properties) {
    if (schema.properties) return "dict[str, JsonValue]";
    return "dict[str, JsonValue]";
  }
  if (Array.isArray(schema.type))
    return schema.type
      .filter((item) => item !== "null")
      .map((item) => pyType({ type: item }, suggestedName, objectNames))
      .join(" | ");
  if (schema.enum) return "JsonValue";
  if (schema.type === "string") return "str";
  if (schema.type === "boolean") return "bool";
  if (schema.type === "integer") return "int";
  if (schema.type === "number") return "float";
  return "JsonValue";
}

function pyFieldName(name) {
  const normalized = String(name)
    .replace(/[A-Z]/g, (value) => `_${value.toLowerCase()}`)
    .replace(/[^A-Za-z0-9_]/g, "_");
  const field = normalized.replace(/^_+/, "") || "value";
  return PY_RESERVED_FIELD_NAMES.has(field) ? `${field}_` : field;
}

const PY_RESERVED_FIELD_NAMES = new Set(["from", "return", "schema"]);

function pyRequiredFieldDefault(name) {
  const field = pyFieldName(name);
  if (field === name) return `Field()`;
  return `Field(validation_alias=AliasChoices(${JSON.stringify(field)}, ${JSON.stringify(name)}), serialization_alias=${JSON.stringify(name)})`;
}

function pyFieldDefault(name) {
  const field = pyFieldName(name);
  if (field === name) return "None";
  return `Field(default=None, validation_alias=AliasChoices(${JSON.stringify(field)}, ${JSON.stringify(name)}), serialization_alias=${JSON.stringify(name)})`;
}

function pyLiteral(value) {
  return JSON.stringify(value, null, 2)
    .replace(/\btrue\b/g, "True")
    .replace(/\bfalse\b/g, "False")
    .replace(/\bnull\b/g, "None");
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const manifest = JSON.parse(readFileSync("testdata/codegen/stagehand_alias_manifest.json", "utf8"));
  const output = "python/tests/stagehand_client_generated/stagehand_client_gen.py";
  const generated = generateClientWithAliasesForPython(
    {
      language: "python",
      name: "StagehandClient",
      custom_commands: manifest.custom_commands,
      custom_alias_objects: manifest.custom_alias_objects,
      default_config: manifest.modcdp_config,
      output,
    },
    manifest.custom_alias_objects ?? [],
    manifest.custom_commands ?? [],
  );
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, generated);
}
